apiVersion: v1
kind: Pod
metadata:
  name: catalog-db
  labels:
    name: catalog-db
spec:
  containers:
    - name: db-noticias-image
      image: GuilhermeM2002/db-noticias-image:1
      ports:
        - containerPort: 3306
      envFrom:
        - configMapRef:
            name: catalog-db-configmap
