apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-deployment
spec:
  selector:
    matchLabels:
      app: catalog
  replicas: 3
  template:
    metadata:
      name: catalog-pod
      labels:
        app: catalog
    spec:
    containers:
      - name: catalog-image
        image: GuilhermeM2002/catalog-image:1
        ports:
          - containerPort: 80
