apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-deployment
spec:
  template:
    metadata:
      name: service
      labels:
        app: service
  replicas: 3
  selector:
    matchLabels:
      app: service
    spec:
      containers:
        - name: service-container
          image: guilhermem2002/service-image:1
          ports:
            - containerPort: 80
      envFrom:
        configMapRef:
          name: service-configmap
      livenessProbe:
        httpGet:
          path: /
          port: 80
        periodSeconds: 10
        failureThreshold: 3
        initialDelaySeconds: 20
      readinessProbe:
        httpGet:
          path: /
          port: 80
        periodSeconds: 10
        failureThreshold: 5
        initialDelaySeconds: 20
      resources:
        requests:
          cpu: 10m